pipeline:
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - /ros_entrypoint.sh catkin_make run_tests"

workspace:
  base: /catkin_ws
  path: src/
