pipeline:
  syntax:
    image: stefanhudelmaier/cppcheck:latest
    when:
      event: push
    commands:
      - cppcheck src/* #--error-exitcode=1
  tests:
    image: ascendntnu/ros-kinetic:1.2
    when:
      event: push
    environment:
      - ASCEND_ENV=production
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make run_tests
  build-only:
    image: ascendntnu/ros-kinetic:1.2
    when:
      event: push
    environment:
      - ASCEND_ENV=production
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make
  publish-docs:
    image: drillster/drone-rsync
    hosts: [ ascendntnu.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/ascend/repos/planning-sim
    when:
      status: success
      event: push
      branch: dev
    script:
      - cd /home/ascend/repos/planning-sim
      - docker-compose run docs
      - mkdir -p /home/ascend/docs/planning-sim
      - cp -R src/AI/Documentation/html/* /home/ascend/docs/planning-sim
  update-ai-status:
    image: appleboy/drone-ssh
    host: ascendntnu.no
    secrets: [ ssh_key ]
    when:
      status: success
      event: push
      #branch: dev
    script:
      - cd /home/ascend/ascendntnu-web/public/assets/ai-status
      - AI_STATUS=5.23
      - echo $DRONE_COMMIT $AI_STATUS >> commit.log
      - curl -o ai-status.svg https://img.shields.io/badge/avg.%20ground%20robots-$AI_STATUS-f80.svg

clone:
  clone:
    image: plugins/git
    when:
      event: push
    recursive: false

workspace:
  base: /catkin_ws/src/planning-sim
  path: ./
