pipeline:
  syntax:
    image: stefanhudelmaier/cppcheck:latest
    when:
      event: push
    commands:
      - cppcheck src/* #--error-exitcode=1
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.4
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh bash -c "source devel/setup.bash && catkin_make run_tests"
  build-only:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.4
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh bash -c "source devel/setup.bash && catkin_make"
  publish-docs:
    image: drillster/drone-rsync
    hosts: [ ascendntnu.no ]
    key: ${RSYNC_KEY}
    secrets: [ rsync_key ]
    target: /home/ascend/repos/planning-sim
    when:
      status: success
      event: push
      branch: dev
    script:
      - cd /home/ascend/repos/planning-sim
      - docker-compose run docs
      - mkdir -p /home/ascend/docs/planning-sim
      - cp -R src/AI/Documentation/html/* /home/ascend/docs/planning-sim

clone:
  clone:
    image: plugins/git
    when:
      event: push
    recursive: false

workspace:
  base: /catkin_ws
  path: src/planning-sim/
