pipeline:
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make run_tests

clone:
  clone:
    image: plugins/git
    when:
      event: push
    recursive: true
    submodule_override:
      src/ai-sim: https://github.com/ascendntnu/ai-sim.git

workspace:
  base: /catkin_ws
  path: src/
