pipeline:
  syntax:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - cppcheck /catkin_ws/src/*
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make run_tests

clone:
  clone:
    image: plugins/git
    when:
      event: push
    recursive: false

workspace:
  base: /catkin_ws
  path: src/
