pipeline:
  clone:
    image: plugins/git
    recursive: true
    submodule_override:
      ai-sim: https://github.com/ascendntnu/ai-sim.git
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make run_tests

workspace:
  base: /catkin_ws
  path: src/
