pipeline:
  syntax:
    image: stefanhudelmaier/cppcheck:latest
    when:
      event: push
    commands:
      - cppcheck src/* --error-exitcode=1
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make run_tests
  publish-docs:
    image: drillster/drone-rsync
    hosts: [ ascendntnu.no ]
    key: "${SSH_KEY}"
    target: /home/ascend/repos/planning-sim
    when:
      status: success
      event: push
      branch: [ dev, feature/publish-docs ]
    script:
      - pwd
      - ls -lah
      - cd /home/ascend/docs
      - mkdir -p planning-sim
      - cd planning-sim
      - pwd

clone:
  clone:
    image: plugins/git
    when:
      event: push
    recursive: false

workspace:
  base: /catkin_ws
  path: src/planning-sim/
