pipeline:
  syntax:
    image: stefanhudelmaier/cppcheck:latest
    when:
      event: push
    commands:
      - cppcheck src/* --error-exitcode=1 --enable=warning
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - cd /catkin_ws
      - /ros_entrypoint.sh catkin_make run_tests

clone:
  clone:
    image: plugins/git
    when:
      event: push
    recursive: false

workspace:
  base: /catkin_ws
  path: src/planning-sim/
