pipeline:
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    when:
      event: push
    commands:
      - /ros_entrypoint.sh cd /catkin_ws && catkin_make run_tests

workspace:
  base: /catkin_ws
  path: src/
