{
    time_chatter_topic: time_chatter,
    ground_robot_topic: groundrobot_chatter,
    drone_topic: drone_chatter,
    control_action_server: control_action_chatter,
    total_competition_time: 600.0
}

