version: '2'

services:
#  nodes:
#    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
#    tty: true
#    volumes:
#      - ./run-docker.sh:/build.sh:ro
#      - .:/catkin_ws/src/planning-sim/:rw
  master:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    container_name: master
    command: bash -c "cd /catkin_ws && roscore"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    network_mode: "host"
  planning:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    container_name: planning
    command: bash -c "cd /catkin_ws && catkin_make && source devel/setup.bash && rosrun planning_ros_sim planning"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    network_mode: "host"
  pc:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    container_name: pc	
    command: bash -c "cd /catkin_ws && catkin_make && source devel/setup.bash && rosrun planning_ros_sim perception_control"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    network_mode: "host"
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    command: bash -c "cd /catkin_ws && catkin_make run_tests"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    network_mode: "host"
