version: '2'

services:
  nodes:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    command: bash -c "cd catkin_ws && catkin_make && source devel/setup.bash && roslaunch planning_ros_sim run_nodes.launch"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    network_mode: "host"
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    command: bash -c "cd /catkin_ws && catkin_make run_tests"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
  gui:
    build:
      context: ./src/ai-sim
      dockerfile: Dockerfile
    tty: true
    command: bash -c "cd /srv/ai-sim/src/ai-sim/ && ./COMPILE_AND_RUN_SIM.sh"
    environment:
      DISPLAY:
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/srv/ai-sim/:rw
    network_mode: "host"
