version: '2'

services:
  nodes:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    command: bash -c "cd /catkin_ws && catkin_make && source devel/setup.bash && roslaunch planning_ros_sim run_nodes.launch"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    network_mode: "host"
  tests:
    image: registry.ascendntnu.no/ascend-ros-kinetic:0.2
    tty: true
    command: bash -c "cd /catkin_ws && catkin_make run_tests"
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
  syntax:
    image: stefanhudelmaier/cppcheck:latest
    tty: true
    command: cppcheck src/* -isrc/ai-sim --error-exitcode=1 --enable=warning
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    working_dir: /catkin_ws/src/planning-sim/
  docs:
    image: nnadeau/docker-doxygen:latest
    tty: true
    volumes:
      - .:/catkin_ws/src/planning-sim/:rw
    working_dir: /catkin_ws/src/planning-sim/
  gui:
    build:
      context: ./src/ai-sim
      dockerfile: Dockerfile
    tty: true
    working_dir: /srv/ai-sim/src/ai-sim/
    environment:
      DISPLAY:
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/srv/ai-sim/:rw
    network_mode: "host"
